[package]
name = "physicsengine"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"  # For parallelization
pyo3 = { version = "0.20", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]